GET http://localhost:3000/problem-logs?page=1&limit=7

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/62568ed3f8cda11636ee0024

###
GET http://localhost:3000/auth/authenticate

###
GET http://localhost:3000/lighting-all

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"hai",
    "email":"lemonilo@gmail.com",
    "password":"lemonilo",
    "age":17,
    "role":"Superadmin",
    "gender":"Man"
}

###
PATCH  http://localhost:3000/users/62568ed3f8cda11636ee0024
Content-Type: application/json

{
    "name":"hai guys"
}

###
DELETE  http://localhost:3000/users/62568fc96205f46e94c9022a

###
POST http://192.168.1.5:3000/location
Content-Type: application/json

{
    "_id" : "6218a11e124fcc9aa0becee1"
}
